(function () {
    'use strict';
    angular.module('Tombola.Games.NoughtsAndCrosses')
        .run(['$templateCache', function ($templateCache) {
            $templateCache.put('partials/player-selection.html', '<div class="playerSelection"> <h2>Game Lobby</h2> <p>Click on the images to change the opponent</p> <div ng-click="playerSelection.selectPlayer(1)" class="{{playerSelection.player1Type}}" ng-model="playerSelection.player1Type"></div> <div ng-click="playerSelection.selectPlayer(2)" class="{{playerSelection.player2Type}}" ng-model="playerSelection.player2Type"></div> <div> <input type="button" value="Start Game!" ng-click="makeNewGame()"> </div> </div>');
            $templateCache.put('partials/game-board.html', '<div ng-controller="GameBoardController"> <h3>Player {{model.currentPlayer}}, please take your turn.</h3> <div class="table" id="board" > <div class="row"> <game-board-square square-number="0" class="cell"></game-board-square> <game-board-square square-number="1" class="cell"></game-board-square> <game-board-square square-number="2" class="cell"></game-board-square> </div> <div class="row"> <game-board-square square-number="3" class="cell"></game-board-square> <game-board-square square-number="4" class="cell"></game-board-square> <game-board-square square-number="5" class="cell"></game-board-square> </div> <div class="row"> <game-board-square square-number="6" class="cell"></game-board-square> <game-board-square square-number="7" class="cell"></game-board-square> <game-board-square square-number="8" class="cell"></game-board-square> </div> </div> <div class="players">Player One: {{model.playerSelection.player1Type}} -- Player Two: {{model.playerSelection.player2Type}} </div> <div> <button ng-click="model.resetGame()" ui-sref="playerSelection">Reset</button> </div> </div>');
            $templateCache.put('partials/game-rules.html', '<div class="gameRules"> <h2>Game Rules</h2> <p>The rules to Noughts and Crosses are very simple and here they are!</p> <p>Player 1 uses Xs and Player 2 uses Os</p> <p>Each player takes turns and places a mark in any square on the board by clicking it</p> <p>The first player to get 3 of their marks in a row going vertically, horizontally or diagonally wins!</p> <p> <br /> <a href="javascript: window.history.go(-1)">Go Back</a> </p> </div>');
            $templateCache.put('partials/game-about.html', '<div class="gameAbout"> <h2>About</h2> <p>Liam Armour</p> <p> <br /> <a href="javascript: window.history.go(-1)">Go Back</a> </p> </div>');
            $templateCache.put('partials/game-win.html', '<div ng-controller="GameBoardController" class="gameRules"> <h1>We have a winner!!</h1> <h3>Player {{model.gameWinner}} won that game!!</h3> <br><br> </div> <img src="images/minion.gif" class="win-image">');
            $templateCache.put('partials/game-draw.html', '<div ng-controller="GameBoardController" class="gameRules"> <h1>We have a Draw!!</h1> <h3>No-one won that game!!</h3> <br><br> </div>');
        }
    ]);

})();